# Generated by Django 3.0.2 on 2020-02-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.TextField()),
                ('joy', models.FloatField()),
                ('sorrow', models.FloatField()),
                ('anger', models.FloatField()),
                ('surprise', models.FloatField()),
                ('like_factor', models.FloatField()),
            ],
        ),
    ]
